nodes_count: "{{ lookup('env', 'NODE_COUNT') | default(3, true) }}"

nodes_name: "{{ lookup('env','NODE_NAME') | default('studentnode', true) }}-"
nodes_image: "{{ lookup('env','IMAGE') | default('Ubuntu Server 18.04 64bit (29.05.2018)', true) }}"
nodes_flavor_name: "{{ lookup('env','NODE_FLAVOR') | default('m1.medium', true) }}"

security_group: "{{ lookup('env','NODE_SEC_GROUP') | default('default', true) }}"
key_name: "{{ lookup('env','KEY') | default('Dennis Mac 2017', true)  }}"

external_network_name: "{{ lookup('env','EXT_NET') | default('ext-net-201', true) }}"
floating_ip_pools: "{{ lookup('env', 'FLOATING_IP_POOL') | default('ext-net-201', true) }}"

router_name: "{{nodes_name}}-router"
subnet_name: "{{nodes_name}}-subnet"
network_name: "{{nodes_name}}-network"

dns_server_1: "{{ lookup('env','DNS_SERVER_1') | default('8.8.8.8', true) }}"
dns_server_2: "{{ lookup('env','DNS_SERVER_2') | default('8.8.4.4', true) }}"

ssh_known_hosts_command: "ssh-keyscan -T 10"
ssh_known_hosts_file: "{{ lookup('env','HOME') + '/.ssh/known_hosts' }}"

generated_server_list_file: "{{ lookup('env','GENERATED_SERVER_LIST') | default('generated-server-list.txt', true) }}"
